rm_referee:
  robot_type: engineer2
  send_ui_queue_delay: 0.05
  add_ui_frequency: 0.5
  add_ui_max_times: 3
  dbus_topic: "/rm_ecat_hw/dbus"
  interactive_data:
  ui:
    trigger_change: []
    fixed:
      - name: "car_line_left"
        config: { type: "line", width: 2, color: "orange",
                  start_position: [ 803, 595 ], end_position: [ 740, 500 ] }
      - name: "car_line_right"
        config: { type: "line", width: 2, color: "orange",
                  start_position: [ 970, 587 ], end_position: [ 1031, 125 ] }
    flash: []